platform :ios, '8.0'
use_frameworks!

pod 'Sugar', git: 'https://github.com/hyperoslo/Sugar'
pod 'Tailor', git: 'https://github.com/zenangst/Tailor'
pod 'GoldenRetriever', git: 'https://github.com/zenangst/GoldenRetriever'
pod 'Hex'
pod 'Compass', git: 'https://github.com/hyperoslo/compass'
pod 'Fakery'
