require "../../core-pods.rb"
source 'https://github.com/CocoaPods/Specs.git'
platform :tvos, '10.0'
use_frameworks!
inhibit_all_warnings!

target "tvOS Dashboard" do
  core_pods
  pod 'Sugar', '~> 2.0'
  pod 'Imaginary', git: 'https://github.com/hyperoslo/Imaginary', branch: 'swift-3'
end
