require "../../core-pods.rb"
source 'https://github.com/CocoaPods/Specs.git'
platform :tvos, '10.0'
use_frameworks!
inhibit_all_warnings!

target "tvOS Dashboard" do
  core_pods
  pod 'Sugar', '~> 3.0'
  pod 'Imaginary', '~> 1.0'
end
