require "../../core-pods.rb"
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target "AppleNews" do
  core_pods
  pod 'Sugar', '~> 2.0'
  pod 'Hue', '~> 2.0'
  pod 'Compass', '~> 4.0'
  pod 'Imaginary', git: 'https://github.com/hyperoslo/Imaginary', :branch => 'swift-3'
  pod 'Fakery', '2.0.0'
  pod 'Transition', git: 'https://github.com/hyperoslo/Transition', :branch => 'swift-3'
end
