source 'https://github.com/CocoaPods/Specs.git'

platform :tvos, '9.2'

use_frameworks!
inhibit_all_warnings!

target "Dashboard" do
  pod 'Sugar'
  pod 'Tailor'
  pod 'Brick'
  pod 'Spots', path: '../../'
  pod 'Imaginary', git: 'https://github.com/hyperoslo/Imaginary'
end
