require "../../core-pods.rb"
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'SpotsNibDemo' do
  core_pods
  pod 'Hue', '~> 2.0'
end
