require "../../core-pods.rb"
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target "Spotify" do
  core_pods
  pod 'Sugar', git: 'https://github.com/hyperoslo/Sugar', :branch =>  'swift-3'
  pod 'Compass', git: 'https://github.com/hyperoslo/Compass', :branch =>  'swift-3'
  pod 'Imaginary', git: 'https://github.com/hyperoslo/Imaginary', :branch =>  'swift-3'
  pod 'Keychain', git: 'https://github.com/hyperoslo/Keychain', :branch => 'swift-3'
  pod 'Whisper', git: 'https://github.com/hyperoslo/Whisper', :branch => 'swift-3'
  pod 'Hue', git: 'https://github.com/hyperoslo/Hue', :branch => 'swift-3'
end
