require "../../core-pods.rb"
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target "Spotify" do
  core_pods
  pod 'Sugar', '~> 3.0'
  pod 'Compass', '~> 4.0'
  pod 'Imaginary', '~> 1.0'
  pod 'Keychain', git: 'https://github.com/hyperoslo/Keychain', :branch => 'swift-3'
  pod 'Whisper', '~> 4.0'
  pod 'Hue', '~> 2.0'
end
