require "../../core-pods.rb"
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target "SpotsFeed" do
  core_pods
  pod 'Sugar', '~> 3.0'
  pod 'Hue', '~> 2.0'
  pod 'Compass', '~> 4.0'
  pod 'Imaginary', '~> 1.0'
  pod 'Fakery', '2.0.0'
end
