source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

target "SpotsFeed" do
  pod 'Sugar'
  pod 'Compass', '2.0.0'
  pod 'Imaginary', git: 'https://github.com/hyperoslo/Imaginary'
  pod 'Cache', git: 'https://github.com/hyperoslo/Cache'
  pod 'Spots', path: '../../'
  pod "Fakery"
end
